name: Release to Maven Central

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Releasing version $VERSION"

      # Single comprehensive build with all checks, tests, and artifacts
      - name: Build, test, and create artifacts
        run: |
          ./gradlew clean build \
            integrationTest \
            jacocoTestReport jacocoTestCoverageVerification \
            javadocJar sourcesJar \
            --no-daemon --stacktrace

      # Import GPG key for signing
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Sign and publish to Maven Central (Central Portal)
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_centralPortalUsername: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          ORG_GRADLE_PROJECT_centralPortalPassword: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: ${{ github.workspace }}/.gnupg/secring.gpg
        run: |
          # Export secret key for Gradle signing
          gpg --export-secret-keys > ${{ github.workspace }}/.gnupg/secring.gpg

          # Publish to Maven Central via Central Portal
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository \
            --no-daemon --stacktrace

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.extract_version.outputs.VERSION }}
          body: |
            ## Release ${{ steps.extract_version.outputs.VERSION }}

            ### Installation

            #### Gradle
            ```kotlin
            dependencies {
                implementation("zm.hashcode:open-payments-java:${{ steps.extract_version.outputs.VERSION }}")
            }
            ```

            #### Maven
            ```xml
            <dependency>
                <groupId>zm.hashcode</groupId>
                <artifactId>open-payments-java</artifactId>
                <version>${{ steps.extract_version.outputs.VERSION }}</version>
            </dependency>
            ```

            ### Changes
            See [CHANGELOG.md](CHANGELOG.md) for details.

            ---
            **Note:** This is a pre-1.0.0 release. The API may change between releases.
          draft: false
          prerelease: ${{ startsWith(steps.extract_version.outputs.VERSION, '0.') }}
          files: |
            build/libs/*.jar
            build/publications/maven/pom-default.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish JavaDoc
        run: |
          ./gradlew javadoc --no-daemon

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          destination_dir: javadoc/${{ steps.extract_version.outputs.VERSION }}

  verify-release:
    name: Verify Maven Central Release
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Maven Central sync
        run: sleep 300  # Wait 5 minutes for Maven Central to sync

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Verify artifact is available
        run: |
          curl -f "https://repo1.maven.org/maven2/zm/hashcode/open-payments-java/${{ steps.extract_version.outputs.VERSION }}/open-payments-java-${{ steps.extract_version.outputs.VERSION }}.pom" || exit 1
          echo "✅ Artifact successfully published to Maven Central!"
